import { Component, OnInit } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

@Component({
  selector: 'lib-icons',
  standalone: true,
  imports: [BrowserModule],
  templateUrl: './icons.component.html',
  styleUrl: './icons.component.css'
})
export class IconsComponent implements OnInit{
  iconSocialMediaList:Array<string>=[];
  iconPluginSocialList:Array<string>=[];
  withOpacity:boolean=false;


  ico22:Array<string>=[];
  ico23:Array<string>=[];
  ico24:Array<string>=[];
  ico26:Array<string>=[];
  ico32:Array<string>=[];
  ico36:Array<string>=[];
  ico40:Array<string>=[];
  ico50:Array<string>=[];
  ico55:Array<string>=[];
  ico60:Array<string>=[];
  ico62:Array<string>=[];
  ico80:Array<string>=[];
  ico90:Array<string>=[];
  ico100:Array<string>=[];
  ico110:Array<string>=[];
  ico150:Array<string>=[];
  icoSm:Array<string>=[];
  icoPluginSocialFacebook:Array<string>=[];

  ngOnInit(): void {
    this.icoSm=[
      "ico-socialmedia-facebook",
      "ico-socialmedia-facebook-zoom",
      "ico-socialmedia-twitter",
      "ico-socialmedia-twitter-zoom",
      "ico-socialmedia-googleplus",
      "ico-socialmedia-youtube",
      "ico-socialmedia-instagram",
      "ico-socialmedia-stumbleupon",
      "ico-socialmedia-reddit",
      "ico-socialmedia-digg",
      "ico-socialmedia-vimeo",
      "ico-socialmedia-delicius",
      "ico-socialmedia-newsvine",
      "ico-socialmedia-foursquare",
      "ico-socialmedia-linkedin",
      "ico-socialmedia-linkedin-zoom",
      "ico-socialmedia-tumblr",
      "ico-socialmedia-pinterest",
      "ico-socialmedia-spotify",
      "ico-socialmedia-flickr",
      "ico-socialmedia-website",
      "ico-socialmedia-email",
      "ico-socialmedia-whatsapp",
      "ico-socialmedia-whatsapp-zoom",
      "ico-socialmedia-telegram",
      "ico-socialmedia-telegram-zoom",
      "ico20-socialmedia-FCB ",
      "ico20-socialmedia-TWT ",
    ]
    this.icoPluginSocialFacebook=[
      "ico-pluginsocial-facebook-comments ",
      "ico-pluginsocial-facebook-page ",
      "ico-pluginsocial-facebook-send ",
      "ico-pluginsocial-facebook-share-button ",
      "ico-pluginsocial-facebook-like ",
      "ico-pluginsocial-facebook-post ",
      "ico-pluginsocial-facebook-comment-embed ",
    ]
    this.ico23=[
      "ico-alert ",
      "ico-success",
      "ico-diet-arrow",
      "ico-circle-plus",
      "ico-circle-plus-minor",
      "ico-circle-minus",
      "ico-circle-red",
      "ico-blue-check",
      "ico-help",
      "ico-add-item",
      "ico-contact-blue ",
      "ico-info",
      "ico-help",
      "ico-note",
      "ico-opt",
      "ico-cart",
      "ico-star-light",
      "ico-star-dark",
      "ico-arrow-light",
      "ico-arrow-dark",
      "ico-tools-light",
      "ico-tools-dark",
      "ico-label-green",
      "ico-label-yellow",
      "ico-label-red",
      "ico-before",
      "ico-after",
      "ico-item-instruction",
      "ico-lis",
      "ico-list.activ",
      "ico-bloc",
      "ico-block.activ",
      "ico23-duplicate-selected",
      "ico23-duplicate",
      "ico-item-on",
      "ico-item-right",
      "ico-item-right-hover",
      "ico-item-hover",
      "ico-item-left",
      "ico-item-left-hover",
      "ico-item-left-b",
      "ico-group",
      "ico-group-hover",
      "ico-group-on",
      "ico-find",
      "ico-find-smaller ",
      "ico-minor-arrow ",
      "ico-minor-arrow-back ",
      "ico-minor-arrow-v-dark ",
      "ico-plus",
      "ico-exit",
      "ico-exit-hover",
      "ico-totalSendSchedule",
      "ico-send",
      "ico-user",
      "ico-user:hover",
      "ico-setaSubMenuBranca ",
      "ico-setaSubMenuBranca:hover",
      "ico-exit2",
      "ico-exit2:hover",
      "ico-arrow-h",
      "ico-arrow-v",
      "ico-arrow-v2",
      "ico-arrow-up-v",
      "ico-arrow-up-v-white",
      "ico-newuser ",
      "ico-newteam ",
      "ico-arrow-fade",
      "ico-arrow-h-white",
      "ico-arrow-h-white-fade",
      "ico-arrow-h-white-fade-back",
      "ico-arrow-v-white",
      "ico-arrow-v-white2",
      "ico-arrow-v-dark",
      "ico-arrow-v-dark-reverse ",
      "ico-success",
      "ico-open",
      "ico-resolved",
      "ico-waiting",
      "ico-customerWaiting",
      "ico-closed",
      "ico-bell",
      "ico-bell-hover",
      "ico-bell-on",
      "ico-up",
      "ico-down",
      "ico-neutral",
      "ico-error-cross",
      "ico-error-cross-small",
      "ico-error-cross-small-white",
      "ico-disabled",
      "ico-edit",
      "ico-moveOrder",
      "ico-moveOrderTrans",
      "ico-arrowDown",
      "ico-contact",
      "ico-contactTrans",
      "ico-item-edit",
      "ico-item-remove",
      "ico-item-detail",
      "ico-add-credit",
      "ico-moveLeft",
      "ico-moveRight",
      "ico-moveLeft-red",
      "ico-moveRight-red",
      "ico-add",
      "ico-config-gray",
      "ico-config-blue",
      "ico-item-remove-grey",
      "ico-funnel",
      "ico-users",
      "ico-schedule",
      "ico-schedule-ab",
      "ico-ballplus",
      "ico-play",
      "ico-pause",
      "ico-sms",
      "ico-filter-rule",
      "ico-filter-field",
      "ico-filter",
      "ico-grid-clean",
      "ico-grid-addvalues",
      "ico-grid-calendar",
      "ico-grid-pause",
      "ico-grid-play",
      "ico-grid-sendtest",
      "ico-grid-report",
      "ico-grid-share",
      "ico-grid-duplicate",
      "ico-grid-technical",
      "ico-grid-contacts",
      "ico-grid-listdetails",
      "ico-grid-contactdetails",
      "ico-refresh",
      "ico-key",
      "ico-gear",
      "ico-trash",
      "ico-gear-white",
      "ico-edit-white",
      "ico-play-white",
      "ico-pause-white",
      "ico-entrada-contato",
      "ico-comportamento-contato",
      "ico-verificacao-diaria",
      "ico-atualizacao-contato",
      "ico-atualizar-dados",
      "ico-pos-clique",
      "ico-tempo",
      "ico-enviar-email",
      "ico-enviar-sms",
      "ico-push",
      "ico-acao",
      "ico-adicionar-trigger",
      "ico-pausar",
      "ico-ativar",
      "ico-relatorio",
      "ico-locked",
      "ico-basket",
      "ico-check",
      "ico-admin",
      "ico-super",
      "ico-closethick",
      "ico-arrowup-red",
      "ico-check-black",
      "ico-chart-black",
      "ico-view-black",
      "ico-folder-plus",
      "ico-folder-minus",
      "ico-file",
      "ico-copy",
      "ico-folder",
      "ico-gearblue",
      "ico-geargray",
      "ico-lapice",
      "ico-setaPath",
      "ico-setaComeBack",
      "ico-setaSubMenu",
      "ico-item",
      "ico-pencil",
      "ico-addvalues-blue",
      "ico-app",
      "ico-arrow-to-bottom",
      "ico-arrow-to-left",
      "ico17-star-full",
      "ico17-star-half",
      "ico17-star-empty",
      "ico-cloud-download",
      "ico-cloud-upload",
      "ico-gray-cloud-download",
      "ico-config-blocked",
      "ico-chat-ballon",
    ]
    this.ico32=[
      "ico32-cursor-border ",
      "ico32-contact",
      "ico32-contact-blue ",
      "ico32-x",
      "ico32-megaphone",
      "ico32-phanton",
      "ico32-contact-purple",
      "ico32-setting-yellow",
      "ico32-setting",
      "ico32-share",
      "ico32-share",
      "ico32-calendar-select",
      "ico32-calendar",
      "ico32-list-select",
      "ico32-list",
      "ico32-importan",
      "ico32-pointer",
      "ico32-group",
      "ico32-filter",
      "ico32-pointer-selected ",
      "ico32-group-selected ",
      "ico32-filter-selected ",
      "ico32-extract-select",
      "ico32-extract",
      "ico32-rotate",
      "ico32-rotate-inv",
    ]
    this.ico36=[
      "ico36-previous",
      "ico36-next"
    ]
    this.ico40=[
      "ico40-pointer",
      "ico40-group",
      "ico40-pointer-selected",
      "ico40-group-selected",
      "ico40-filter",
      "ico40-filter-selected",
      "ico40-form",
      "ico40-form-selected",
      "ico40-people",
      "ico40-people-select",
      "ico40-user-key",
      "ico40-user-key-select",
      "ico40-notkey",
      "ico40-notkey-select",
      "ico40-lamp",
      "ico40-check-green",
    ]
    this.ico50=[
      "ico50-config-view",
      "ico50-config-blocked",
      "ico50-share ",
      "ico50-permission ",
      "ico50-config-sender",
      "ico50-config-replyto",
      "ico50-cell-flip"
    ]
    this.ico55=[
      "ico55-chat",
      "ico55-telephone",
      "ico55-preview",
      "ico55-desktop",
      "ico55-mobile",
      "ico55-mobile-flip",
      "ico55-play",
      "ico55-basket",
    ]
    this.ico60=[
      "ico60-email-fast ",
      "ico60-email-slow ",
      "ico60-ab-message ",
      "ico60-ab-subject ",
      "ico60-ab-sender ",
      "ico60-ab-dynamic ",
      "ico60-tag ",
      "ico60-email-pontual ",
      "ico60-email-clock-fast",
      "ico60-email-clock-slow",
      "ico60-email-editor-src",
      "ico60-email-editor-saved",
      "ico60-email-dragdrop",
      "ico60-email-dragdrop-saved",
      "ico60-email-upload",
      "ico60-email-upload-zip",
      "ico60-email-url-src",
      "ico60-email-url-send",
      "ico60-email-prev-send",
      "ico60-email-model-send",
      "ico60-email-letters",
      "ico60-popover",
      "ico60-scrollbox",
      "ico60-topbar"
    ]
    this.ico62=[
      "ico62-lamp"
    ]
    this.ico80=[
      "ico80-email-configure",
      "ico80-email-prepare",
      "ico80-info-public"
    ]
    this.ico90=[
      "ico90-big-notkey",
      "ico90-big-people"
    ]
    this.ico100=[
      "ico100-dash-send",
      "ico100-dash2-send",
      "ico100-clock-send"
    ]

    this.ico110=[
      "ico-submenu-newSend",
      "ico-submenu-newSend-hover",
      "ico-submenu-filter",
      "ico-submenu-filter-hover",
      "ico-submenu-import",
      "ico-submenu-import-hover",
      "ico-submenu-statistics",
      "ico-submenu-statistics-hover",
      "ico-submenu-search",
      "ico-submenu-search-hover",
      "ico-submenu-history",
      "ico-submenu-history-hover",
      "ico-submenu-models",
      "ico-submenu-models-hover",
      "ico-submenu-workflow",
      "ico-submenu-workflow-hover",
      "ico-submenu-campaigns",
      "ico-submenu-campaigns-hover",
      "ico-submenu-testAB",
      "ico-submenu-testAB-hover",
      "ico-submenu-schedule",
      "ico-submenu-schedule-hover",
      "ico-submenu-faq",
      "ico-submenu-faq-hover",
      "ico-submenu-called",
      "ico-submenu-called-hover",
      "ico-submenu-videoTutorial",
      "ico-submenu-videoTutorial-hover",
      "ico-submenu-wiki",
      "ico-submenu-wiki-hover",
      "ico-submenu-dataBase",
      "ico-submenu-dataBase-hover",
      "ico-submenu-chat",
      "ico-submenu-chat-hover",
      "ico-submenu-consolidated",
      "ico-submenu-consolidated-hover",
      "ico-submenu-extract",
      "ico-submenu-extract-hover",
      "ico-submenu-landingpage",
      "ico-submenu-landingpage-hover",
      "ico-submenu-sms",
      "ico-submenu-sms-hover",
      "ico110-ref55",
      "ico110-ref56",
      "ico110-ref57",
      "ico110-ref58",
      "ico110-ref59",
      "ico110-ref60",
      "ico110-ref61",
      "ico110-ref62",
      "ico110-ref63",
      "ico110-ref64",
      "ico110-ref65",
      "ico110-ref66",
      "ico110-ref67",
      "ico110-ref68",
      "ico110-ref69",
      "ico110-ref70",
      "ico110-ref71",
      "ico110-ref72",
      "ico110-ref73",
      "ico110-ref74",
      "ico110-ref75",
      "ico110-ref76",
      "ico110-ref77",
      "ico110-ref78",
      "ico110-ref79",
      "ico110-ref80",
      "ico110-ref81",
      "ico110-ref82",
      "ico110-ref83",
      "ico110-ref84",
      "ico110-ref85",
      "ico110-ref86",
      "ico110-ref87",
      "ico110-ref88",
      "ico110-ref89",
      "ico110-ref90",
      "ico110-ref91",
      "ico110-ref92",
      "ico110-ref93",
      "ico110-ref94",
      "ico110-ref95",
      "ico110-ref96",
      "ico110-ref97",
      "ico110-ref98",
      "ico110-ref99",
      "ico110-ref100",
      "ico110-ref101",
      "ico110-ref102",
      "ico110-ref103",
      "ico110-ref104",
      "ico110-ref105",
      "ico110-ref106",
      "ico110-ref107",
      "ico110-ref108",
      "ico110-ref109",
      "ico110-ref110",
      "ico110-ref111",
      "ico110-ref112",
      "ico110-ref113",
      "ico110-ref114",
      "ico110-ref118",
      "ico110-ref120",
      "ico100-telephone",
      "ico110-dispositives",
      "ico110-expirationtime"
    ]

    this.ico150=[
      "ico150-icon-help"
    ]
  }
}
